#项目服务器配置
spring:
  application:
    name: shop-api
  datasource: # ????????
    type: com.zaxxer.hikari.HikariDataSource          # ??????HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql ??
    url: jdbc:mysql://127.0.0.1:3306/shop_online?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8 # ?8?
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000       # ????????????(??)?????????????????SQLException,??30?
      minimum-idle: 5                 # ?????
      maximum-pool-size: 20           # ?????
      auto-commit: true               # ????
      idle-timeout: 600000            # ?????????(??)???????(retired) ???10??
      pool-name: DateSourceHikariCP   # ?????
      max-lifetime: 1800000           # ???????(??)?????????????(retired),???30?? 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    #redis数据库索引(默认为0)
    database: 0
    #redis服务器地址
    host: 127.0.0.1
    #redis服务器连接端口
    port: 6379
    #redis连接密码
    password: